# Compiles Trail.hlsl with fxc (Windows SDK) and embeds the bytecode in ..\Shaders.cs.
# Run after editing the shader; the product never compiles HLSL at run time.
param([string]$Fxc)
$ErrorActionPreference = 'Stop'

if (-not $Fxc) {
    $Fxc = Get-ChildItem 'C:\Program Files (x86)\Windows Kits\10\bin\*\x64\fxc.exe' -ErrorAction SilentlyContinue |
        Sort-Object FullName -Descending | Select-Object -First 1 -ExpandProperty FullName
}
if (-not $Fxc -or -not (Test-Path -LiteralPath $Fxc)) { throw 'fxc.exe not found; pass -Fxc <path>.' }

$source = Join-Path $PSScriptRoot 'Trail.hlsl'
$temp = Join-Path ([IO.Path]::GetTempPath()) ('mgt-shaders-' + [Guid]::NewGuid())
New-Item -ItemType Directory -Path $temp | Out-Null
try {
    $entries = @(
        @{ Name = 'VertexShader'; Entry = 'VS'; Profile = 'vs_4_0' },
        @{ Name = 'PixelShader'; Entry = 'PS'; Profile = 'ps_4_0' }
    )
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('// <auto-generated> by Shaders\build-shaders.ps1 from Shaders\Trail.hlsl. Do not edit. </auto-generated>')
    $lines.Add('namespace MouseGlowTrail;')
    $lines.Add('')
    $lines.Add('internal static class Shaders')
    $lines.Add('{')
    foreach ($shader in $entries) {
        $output = Join-Path $temp ($shader.Entry + '.cso')
        & $Fxc /nologo /T $shader.Profile /E $shader.Entry /O3 /WX /Qstrip_reflect /Qstrip_debug /Qstrip_priv /Fo $output $source
        if ($LASTEXITCODE -ne 0) { throw "fxc failed for $($shader.Entry)" }
        $bytes = [IO.File]::ReadAllBytes($output)
        $lines.Add("    public static ReadOnlySpan<byte> $($shader.Name) =>")
        $lines.Add('    [')
        for ($i = 0; $i -lt $bytes.Length; $i += 16) {
            $count = [Math]::Min(16, $bytes.Length - $i)
            $chunk = ($bytes[$i..($i + $count - 1)] | ForEach-Object { '0x{0:X2}' -f $_ }) -join ', '
            $lines.Add("        $chunk,")
        }
        $lines.Add('    ];')
        $lines.Add('')
        Write-Host ("{0}: {1} bytes" -f $shader.Entry, $bytes.Length)
    }
    $lines.RemoveAt($lines.Count - 1)
    $lines.Add('}')
    $target = Join-Path (Split-Path $PSScriptRoot -Parent) 'Shaders.cs'
    [IO.File]::WriteAllLines($target, $lines, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "wrote $target"
}
finally {
    Remove-Item -LiteralPath $temp -Recurse -Force
}
